# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core_spanish.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hola']

# %% ../nbs/01_core_spanish.ipynb 3
def foo(): pass

# %% ../nbs/01_core_spanish.ipynb 4
def say_hola(to):
    "Say hola to somebody"
    return f'Hola {to}!'
